language: node_js
node_js:
  - "0.10"

before_install:
  - "npm install -g istanbul codeclimate-test-reporter"

addons:
  code_climate:
    repo_token: 81c0631d5c48d85443ea5fd0843817847c68f2e60c10280653d30819242bd899

script:
  - "npm run coverage"

after_script:
  - "cat ./coverage/lcov.info | codeclimate"